server:
  port: 8083
spring:
  datasource:
    password: root
    url: jdbc:mysql://localhost:3306/coupondb
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
     hibernate:
      format-sql: true
      
  application:
    name: coupon-service
    
    
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    
    service-url:
      defaultZone: http://localhost:8761/eureka
      
      
      