eureka:
  client:
    register-with-eureka: true
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost
    prefer-ip-address: true
      
      
spring:
  profiles:
    active: native
  application:
    name: config-server
    
server:
  port: 8888
  
  



    
  
  
  
  
  
  
    
